[package]
name = "y2025"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"




[[bin]]
name = "day01"
path = "src/bin/day01.rs"

[[bin]]
name = "day02"
path = "src/bin/day02.rs"

[[bin]]
name = "day03"
path = "src/bin/day03.rs"







